### ISSUE TITLE
Bogoljubo{v,w} inconsistency

### ISSUE THREAD

**Issue by xaverh** [lichess-org/chess-openings#157]
Currently, there are a instances, where Bogoljubo{v,w} is spelled with either v or w.
It would be reasonable to unify the spelling but I'm not quite sure in which direction.
Bogoljubow makes sense as he was naturalized German citizen and e.g. that's how it is written on his grave, cf. https://en.wikipedia.org/wiki/Efim_Bogoljubow#/media/File:Bogoljubow_Grabstein_Triberg.JPG
On the other hand, the spelling Bogoljubov is more readable to non-German speakers and also more consistent with the handling of Russian names in this library in general (cf. Yusupov v Jussupow).

**Comment by niklasf** [comment]
Looking to https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style#Spelling_and_romanization for guidance, I think we should use `w` in this case, because based on your link there is an established spelling in the Latin alphabet. For names where this is not the case, we would fall back to systematic translateration, using `v`.
