### ISSUE TITLE
Misc issues and improvements

### ISSUE THREAD

**Issue by niklasf** [lichess-org/chess-openings#46]
Forwarding some potential issue with an earlier version of the database:

> * [ ] Pirc Defense being 1. e4 d6 makes no sense. The Pirc is 1. e4 d6 2. d4 Nf6 3. Nc3 g6
> * [ ] The King's Indian Defense is some exchange variation? It should just be 1. d4 Nf6 2. c4 g6 3. Nc3 Bg7 4. e4 d6
> * [ ] Queen's Gambit Accepted: Just 1. d4 d5 2. c4 dxc4
> * [ ] Horwitz Defense is 1. d4 e6, which is highly transpositional. I don't get why it's some weird Englund gambit (1. d4 e5 2. c4)
> * [ ] Nimzo-Indian Defense: It seems like it's a b6 variation. The Nimzo-Indian Defense is just 1. d4 Nf6 2. c4 e6 3. Nc3 Bb4
> * [ ] The Blackmar-Diemer Gambit is just 1. d4 d5 2. e4
> * [ ] IDK why there's a standalone KG. It's either accepted or declined :P IG some programmatic thing where variations which weren't included get their own category
> * [ ] 1. d4 Nf6 2. c4 d6 3. Nc3 e5 4. Nf3 Nbd7 5. e4 is the Old Indian Defense. Maybe could be cut off on move 3 as that's still unique for the OID

cc @truthdoc

**Comment by fynsta** [comment]
> Pirc Defense being 1. e4 d6 makes no sense. The Pirc is 1. e4 d6 2. d4 Nf6 3. Nc3 g6
- All of the sources here are contradictory, [Wikipedia](https://en.wikipedia.org/wiki/Pirc_Defence) agrees that it should be only after 1. e4 d6 2. d4 Nf6 3. Nc3 g6. Other sites like [365Chess](https://www.365chess.com/eco/B07-B09_Pirc_defence) say 1. e4 d6 2. d4 Nf6 3. Nc3 and also [ChessTempo](https://old.chesstempo.com/gamedb/opening/1536) defines it as 1. e4 d6 2. d4 Nf6. And finally there is also the option of just the two first moves 1. e4 d6, like at [Wikibooks](https://en.wikibooks.org/wiki/Chess_Opening_Theory/1._e4/1...d6) or [chess.com](https://www.chess.com/openings/Pirc-Defense).
Probably all of these would be acceptable choices, we just need to decide what we like best. It might make sense to cut off at 1. e4 d6 2. d4 Nf6, because all subvariations in the list begin there (see Roscher Gambit). Or take the full 6 moves, and remove the Roscher Gambit from the Pirc namespace :) 


> The King's Indian Defense is some exchange variation? It should just be 1. d4 Nf6 2. c4 g6 3. Nc3 Bg7 4. e4 d6
- I don't get this? There are a lot of positions for King's Indian Defense in the database, and the first that comes up is 1. d4 Nf6 2. c4 g6 3. Nc3. Why should it be this super long line that is given here? (actually, according to [Wikipedia](https://en.wikipedia.org/wiki/King%27s_Indian_Defence) it should be only 1. d4 Nf6 2. c4 g6, maybe we should change that)

> Queen's Gambit Accepted: Just 1. d4 d5 2. c4 dxc4
- That's exactly how it's in the database, plus one transposition for 1. d4 d5 2. c4 dxc4 3. Nf3 Nf6

> Horwitz Defense is 1. d4 e6, which is highly transpositional. I don't get why it's some weird Englund gambit (1. d4 e5 2. c4)
- What's the problem here? The Englund Gambit does not have much to do with the Horwitz Defense? 

> Nimzo-Indian Defense: It seems like it's a b6 variation. The Nimzo-Indian Defense is just 1. d4 Nf6 2. c4 e6 3. Nc3 Bb4
- Again, that's how it is in the database. I don't even know where they see b6?

> The Blackmar-Diemer Gambit is just 1. d4 d5 2. e4
- Also how it's in the database. But I did see that it is just called Blackmar Gambit there, I renamed it now

>  IDK why there's a standalone KG. It's either accepted or declined :P IG some programmatic thing where variations which weren't included get their own category
- Uhm, why not?  On the third ply, there is no Accepted/Declined yet because black has not responded yet: [Wikipedia](https://en.wikipedia.org/wiki/King%27s_Gambit) 

> 1. d4 Nf6 2. c4 d6 3. Nc3 e5 4. Nf3 Nbd7 5. e4 is the Old Indian Defense. Maybe could be cut off on move 3 as that's still unique for the OID
- Wikipedia cuts off after move 2, and so does every other source I found [Wikipedia](https://en.wikipedia.org/wiki/Old_Indian_Defense). I did see that we have one variation where we declare it one move earlier, I deleted that one. But I don't know what the original problem here was, exactly?


So overall, most of these points really do not hold water... Maybe people should do a quick fact check to see what consensus opinion is, because everyone might have a different opinion about which position is called what.
